name: mcqueen-bmvc
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.1
  - attrs=21.4.0
  - blas=1.0
  - blinker=1.4
  - bokeh=2.4.3
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - certifi=2021.10.8
  - cffi=1.15.0
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - dataclasses=0.8
  - ffmpeg=4.3
  - freetype=2.11.0
  - frozenlist=1.2.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - ncurses=6.3
  - nettle=3.7.3
  - numpy-base=1.21.5
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1m
  - pillow=8.4.0
  - pip=21.2.4
  - pyasn1=0.4.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.7
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - readline=8.1.2
  - requests-oauthlib=1.3.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.11
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tornado=6.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - audioread==2.1.9
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - black==21.12b0
    - bleach==4.1.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.10
    - click==8.0.3
    - cycler==0.11.0
    - cython==0.29.27
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.3
    - executing==0.8.2
    - filelock==3.9.0
    - fonttools==4.31.2
    - gdown==4.6.3
    - google-auth==2.5.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - importlib-metadata==4.10.1
    - iniconfig==1.1.1
    - ipdb==0.13.9
    - ipykernel==6.7.0
    - ipython==8.0.1
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonpatch==1.32
    - jsonpointer==2.2
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - kaleido==0.2.1
    - kiwisolver==1.4.2
    - kmeans-pytorch==0.3
    - librosa==0.7.1
    - llvmlite==0.37.0
    - markdown==3.3.6
    - markupsafe==2.0.1
    - matplotlib
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbclient==0.5.10
    - nbconvert==6.4.1
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - notebook==6.4.8
    - numba==0.54.1
    - numpy
    - oauthlib==3.1.1
    - packaging==21.3
    - pandas==1.4.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.4.1
    - plotly==5.5.0
    - pluggy==1.0.0
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.26
    - protobuf==3.19.4
    - ptyprocess==0.7.0
    - pulp==2.7.0
    - pure-eval==0.2.2
    - py==1.11.0
    - pyasn1-modules==0.2.8
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pytest==6.2.5
    - python-dateutil==2.8.2
    - pytorchcv==0.0.67
    - pytz==2021.3
    - pyzmq==22.3.0
    - requests==2.27.1
    - resampy==0.2.2
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sklearn==0.0
    - sonopy==0.1.2
    - soundfile==0.10.3.post1
    - soupsieve==2.3.2.post1
    - stack-data==0.1.4
    - tenacity==8.0.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboardx==2.1
    - terminado==0.13.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - toml==0.10.2
    - tomli==1.2.3
    - torch-intermediate-layer-getter==0.1.post1
    - torch-tb-profiler==0.3.1
    - torchfile==0.1.0
    - torchnet==0.0.4
    - torchsummary==1.5.1
    - torchviz==0.0.2
    - tqdm==4.64.1
    - traitlets==5.1.1
    - urllib3==1.26.8
    - visdom==0.1.8.9
    - warmup-scheduler
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - werkzeug==2.0.2
    - zipp==3.7.0
